version: '3'

services:
  django:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    env_file:
      - ./backend/.env
    container_name: django-be
    command: /bin/sh -c "docker/start_django.sh"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
