# Generated by Django 4.2 on 2023-04-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_question_questionchoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
