# Generated by Django 4.2 on 2023-04-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_alter_lesson_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='slug',
            field=models.CharField(blank=True, max_length=512, unique=True),
        ),
    ]
