# Generated by Django 4.2 on 2023-04-23 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_alter_questionchoice_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='stripped_content',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
